--liquibase formatted sql
--changeset root:1

CREATE TABLE `dnitygodnia` (
  `DZIEN_ID` int NOT NULL,
  `DZIEN_NAZWA` varchar(45) NOT NULL,
  `DZIEN_SKROT` varchar(45) NOT NULL,
  PRIMARY KEY (`DZIEN_ID`),
  UNIQUE KEY `DZIEN_ID_UNIQUE` (`DZIEN_ID`),
  UNIQUE KEY `DZIEN_NAZWA_UNIQUE` (`DZIEN_NAZWA`),
  UNIQUE KEY `DZIEN_SKROT_UNIQUE` (`DZIEN_SKROT`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci