--liquibase formatted sql
--changeset root:9

CREATE TABLE `zajęcia` (
  `ZAJ_ID` int NOT NULL AUTO_INCREMENT,
  `ZAJ_CZASROZ` time NOT NULL,
  `ZAJ_CZASZAK` time NOT NULL,
  `PRAC_ID` int NOT NULL,
  `SALA_ID` int NOT NULL,
  `DZIEN_ID` int NOT NULL,
  `PRZ_ID` int NOT NULL,
  PRIMARY KEY (`ZAJ_ID`),
  UNIQUE KEY `ZAJ_ID_UNIQUE` (`ZAJ_ID`),
  KEY `PRZ_ID_idx` (`PRZ_ID`),
  KEY `PRAC_ID_idx` (`PRAC_ID`),
  KEY `SALA_ID_idx` (`SALA_ID`),
  KEY `DZIEN_ID_idx` (`DZIEN_ID`),
  CONSTRAINT `DZIEN_ID` FOREIGN KEY (`DZIEN_ID`) REFERENCES `dnitygodnia` (`DZIEN_ID`),
  CONSTRAINT `PRAC_ID` FOREIGN KEY (`PRAC_ID`) REFERENCES `pracownicy` (`PRAC_ID`),
  CONSTRAINT `PRZ_ID` FOREIGN KEY (`PRZ_ID`) REFERENCES `przedmioty` (`PRZ_ID`),
  CONSTRAINT `SALA_ID` FOREIGN KEY (`SALA_ID`) REFERENCES `sale` (`SALA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci