--liquibase formatted sql
--changeset root:14

--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Klucze do sali nr 1 w dziekanacie', '1');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Zapasowe klucze do sali 1', '1');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Klucze do sali nr 2 w dziekanacie', '4');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Zapasowe klucze do sali 2', '4');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Klucze do sali nr 3 w dziekanacie', '5');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Zapasowe klucze do sali 3', '3');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Klucze do sali nr 4 w dziekanacie', '6');
--INSERT INTO `portiernia`.`klucze` (`KLUCZ_ILOSC`, `SALA_ID`) VALUES ('Zapasowe klucze do sali 4', '6');
